### ISSUE TITLE
official code

### ISSUE THREAD

**Issue by ghost** [gaborvecsei/SLE-GAN#6]
noticed you are working of the paper, are you aware the official code is released and accessible through this google drive link? https://drive.google.com/drive/folders/1nCpr84nKkrs9-aVMET5h8gqFbUYJRPLR

**Comment by gaborvecsei** [comment]
@ak9250 Yes I am aware, and I took only a super quick peak and did not use anything from it because of the following reasons:
- The basics (architecture and training) differs from what I saw in the paper (or just the code is quite messy and I could not understand at that quick glance)
- I wanted to do the reproduction based on the paper only. This is how I can see how well written a paper is.
